### ISSUE TITLE
create website

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#1]
Using the figma designs, create a minimal website with the following features:

* WYSWIG for creating a network topology
  * A user should be able to drag and drop nodes and draw edges between the nodes
  * Provide a way for the user to download the file
  * bonus: allow the user to launch the graph directly from the website
* A page for monitoring a running warnet simulation
  * Something simple to provide the user feedback that something is happening
  * bonus: launch a scenario on the already running network

**Comment by josibake** [comment]
some resources: 

* https://js.cytoscape.org/
* https://christophergandrud.github.io/networkD3/#simple
* https://live.yworks.com/demos/input/custom-drag-and-drop/index.html

altho yfiles seems like a paid service. D3 might be the best choice here, anything we can use to create the graph and then we can translate it into graphml

**Comment by josibake** [comment]
Just as a reminder from our call, lets keep the features for the front end limited so we can get something end to end working by thursday

**Comment by willcl-ark** [comment]
Viva https://warnet.dev/
