### ISSUE TITLE
RPC, other commands can throw errors if docker-compose isnt done building yet

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#100]
We should be polite and catch these errors and send a message to the caller.

**Comment by willcl-ark** [comment]
Yes, I was looking at state (of Network) earlier as CI of RPC calls without it is... trickier

**Comment by pinheadmz** [comment]
adding to this: `warnet` server should probably exit immedeately if it can't find docker running

**Comment by willcl-ark** [comment]
We should also add an abort to from_file if a command fails, or something

**Comment by willcl-ark** [comment]
Closing as compose gone
