### ISSUE TITLE
frontend:scrollbar should only show when there is an overflow in the sidebar

### ISSUE THREAD

**Issue by Extheoisah** [bitcoin-dev-project/warnet#106]
the UI of the sidebar needs a revamp to only show the scrollbar in the side bar when there is an overflow (more nodes in the sidebar that can fit the UI space)

**Comment by 0tuedon** [comment]
Hey @Extheoisah, i don't quite understand this issue, could you share a visual on where the scroll is showing currently

**Comment by Extheoisah** [comment]
> Hey @Extheoisah, i don't quite understand this issue, could you share a visual on where the scroll is showing currently

![Screenshot 2023-09-13 at 10 19 15](https://github.com/bitcoin-dev-project/warnet/assets/60826700/17271b2f-9242-42f0-97af-cb6275f1b2ff)
