### ISSUE TITLE
mobile landing page issues (android)

### ISSUE THREAD

**Issue by adamjonas** [bitcoin-dev-project/warnet#125]
Reports from @aassoiants that the landing page doesn't load on android chrome and brave browsers:

![Screenshot_20230913_105442_Chrome](https://github.com/bitcoin-dev-project/warnet/assets/755825/002865b1-0b41-4f32-80c5-91102006995c)
![Screenshot_20230913_105526_Samsung_Internet](https://github.com/bitcoin-dev-project/warnet/assets/755825/f5866ca9-08a1-4981-a5c5-15123afb296b)

cc @IgboPharaoh

**Comment by igbopharaoh** [comment]
#131  fixes this issue
