### ISSUE TITLE
"Pool overlaps with other one on this address space"

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#134]
You'll see this error if you try to start a new network, i.e. maybe you ran a network named "warnet" previously but it has been shut down in some way that is NOT `docker-compose down`. Even though the containers may be stopped and deleted, the network may still exist and that occupies our subnet `100....`.

**Comment by pinheadmz** [comment]
maybe, all new networks should use a unique subnet prefix. Then we'd have 0-255 possible networks (minus whatever prefixes like 10, 192, etc are "unroutable")

**Comment by willcl-ark** [comment]
I think this would be closed by #303 ?

Now the backend handles it all automagically (except proper cleanup, I guess)

**Comment by matthew-chaincode** [comment]
blah blah spam

**Comment by willcl-ark** [comment]
Closing as we removed official compose support
