### ISSUE TITLE
website example graphs n<=50

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#151]
100 is a bit many for a single machine

**Comment by willcl-ark** [comment]
ping @Emmanuel-Develops 

I can generate these for you if you like?

**Comment by Emmanuel-Develops** [comment]
> ping @Emmanuel-Develops
> 
> I can generate these for you if you like?

yeah, sure thing Will !

I can replace the 100 nodes graph on the frontend with them

**Comment by willcl-ark** [comment]
Closign for now to reduce clutter
