### ISSUE TITLE
Use secrets module instead of random for generating private key

### ISSUE THREAD

**Issue by Riahiamirreza** [bitcoin-dev-project/warnet#169]
https://github.com/bitcoin-dev-project/warnet/blob/33c06db599bd3b25360c7f90c771393b06fcb0b8/src/test_framework/key.py#L330-L332

Not sure how much does this private key is important, but shouldn't it be generated using a more secure PRNG? Something like `secrets`. [Python documentation](https://docs.python.org/3/library/random.html) discourages usage of `random` module for security purposes.
The following may can be a replacement for the current function:
```python

 def generate_privkey(): 
     """Generate a valid random 32-byte private key.""" 
     import secrets
     return (secrets.randbits(256) % SECP256K1_ORDER).to_bytes(32, 'big')
```

**Comment by pinheadmz** [comment]
The entire `src/test_framework` directory is imported from Bitcoin Core. We don't want to make any modifications because it would mean continuous maintenance. We're optimizing for performance here, not security.

**Comment by willcl-ark** [comment]
Closing as wontfix.

Thanks for the report though @Riahiamirreza
