### ISSUE TITLE
Properly dockerize the warnet-rpc server

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#179]
In https://github.com/bitcoin-dev-project/warnet/pull/178 , I'm creating `Dockerfile_rpc` by copying in the whole directory which results in a huge image. This can be done much better. Ideally, this image should also get built and pushed in the `scripts/build_images.sh` script

**Comment by willcl-ark** [comment]
I think we can close this now. Image still not size-optimised, but since #301 it's not auto-built from merges to main and PRs to this repo.
