### ISSUE TITLE
deploy a warnet as a helm chart

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#18]
not sure the best way to do this but one idea is convert a docker-compose.yml to a helm chart using https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

Theres also https://github.com/scaling-lightning/

**Comment by willcl-ark** [comment]
Closing as we don't have any immediate plans to implement a help chart for now.

LMK if you want it re-opened :)
