### ISSUE TITLE
Automate all of the configs

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#180]
In https://github.com/bitcoin-dev-project/warnet/pull/178 , the rpc server is deployed manually (as well as the rbac-config.yaml). Ideally, I'd expect something more like the following:

1. Some sort of "init" command which deploys the RPC server along with the appropriate configs (rbac)
2. Ideally, the warnet-rpc has its own service account, so the permissions are restricted to just that pod
3. This could be in the default namespace, or a "warnet" namespace, and then different warnet topologies can be deployed as their own namespaces?

**Comment by willcl-ark** [comment]
@m3dwards is this still the case in the k8s branch?

**Comment by m3dwards** [comment]
Yes it's still the case.

**Comment by willcl-ark** [comment]
I think this can be closed now ping @mplsgrant @josibake ? We have namespaceing, and committed to supporting a single network at a time?

**Comment by josibake** [comment]
I think this can be closed now that all config is managed via helm. I think at this point , supporting one "network," where network is a set of bitcoin nodes that can discover each other via p2p, makes the most sense to me.
