### ISSUE TITLE
Docs, docs, docs! 

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#187]
No docs for k8s at the moment :sweat_smile:

**Comment by vjurcutiu** [comment]
I'm looking to contribute to some docs. Do you collaborate with external writers?

**Comment by willcl-ark** [comment]
Hey @vjurcutiu, sure we would welcome docs from any contributors!

You could start by looking at https://github.com/bitcoin-dev-project/warnet/issues/191 or are welcome to document any part of setup or usage you think is lacking.

edit: the k8s documentation is somewhat included in this PR (github comments), but as-yet undocumented in the repo: https://github.com/bitcoin-dev-project/warnet/pull/178

**Comment by vjurcutiu** [comment]
Thanks @willcl-ark, I will take a look and see where I can contribute.

**Comment by willcl-ark** [comment]
Going to close this now, as we have _some_ docs and _some_ `just` commands. (We could always use more, but not sure this issue is useful)
