### ISSUE TITLE
Fix IP addresses 

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#189]
Currently, we still have a method that randomly generates a fake IP address if `Tank._ipv4` is None. To get around this, I'm waiting for the pods to spin up and then getting the IP and setting it on the tank, which is pretty gross and will be super slow when spinning up 100s of nodes. We should move all the IP functions into the abstract base class , and grab the IP directly from the container when we need it (same as we were doing in docker land).

**Comment by willcl-ark** [comment]
I think this would be moot with #303 

What did you want IP addresses for? We using hostnames now yo!

**Comment by willcl-ark** [comment]
Closing as we use hostnames externally and patches on bitcoind
