### ISSUE TITLE
Add log aggregation

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#2]
For a running warnet, ship debug logs back to a central server. This should include:

* Debug logs
* bonus: USDT tracepoints per node, all aggregated back to the logging server
  * this gives us data on p2p messages

**Comment by willcl-ark** [comment]
Going to try promtail

**Comment by willcl-ark** [comment]
> bonus: USDT tracepoints per node, all aggregated back to the logging server

0xB10C has been working on an RPC-based (as opposed to tracing-based) addrman-observer over the last few days. Once bitcoin/bitcoin/pull/28523 is merged, you'd be able visualize the addrman of each warnet tank.

**Comment by 0xB10C** [comment]
> 0xB10C has been working on an RPC-based (as opposed to tracing-based) addrman-observer over the last few days. Once [bitcoin/bitcoin/pull/28523](https://github.com/bitcoin/bitcoin/pull/28523) is merged, you'd be able visualize the addrman of each warnet tank.

You probably need to run a proxy like https://github.com/0xB10C/addrman-observer/issues/4 as I don't think accessing the `getrawaddrman` RPC from the browser is a good idea (or even possible). This needs another container but will allow accessing `n` warnet nodes. It will be similar in terms of configuration like fork-observer.

I'll be developing such a proxy and can also take care of packaging it for docker. I'll need the proxy anyways for my monitoring.

**Comment by pinheadmz** [comment]
closed by #133
