### ISSUE TITLE
Automatically build warnet-rpc images for k8s

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#207]
The rpc image (https://hub.docker.com/r/bitcoindevproject/warnet-rpc) has been manually built and pushed.

They should be automatically built and tagged with changes or releases to warnet.

One option would be to make a docker image with tag whenever the github code is tagged and a manual step to update the latest tag.

**Comment by willcl-ark** [comment]
I think it would only warrant when changes to the build script or the Docker Compose file are detected, or at Bitcoin Core version bump time.

That said, where is the k8s build script? I see one in the repo for the docker images, but I guess there is one for k8s too?

**Comment by m3dwards** [comment]
I think this is the script: https://github.com/bitcoin-dev-project/warnet/pull/206/files

**Comment by willcl-ark** [comment]
I should document the dev mode image...

**Comment by willcl-ark** [comment]
This was completed in #301 (and followup)
