### ISSUE TITLE
Find alternative to port mapping RPC on k8s

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#208]
Right now to connect to the RPC on k8s you have to port map from your cluster to local 9276 which is what warcli is expecting.

This does not feel very elegant, we should investigate an alternative. Perhaps use ingress / loadbalancer or a tunneling project that could be integrated into the cli tool?

**Comment by willcl-ark** [comment]
This is now not an issue, but I opened #587 to track adding ingress.

Going to close this one
