### ISSUE TITLE
Run a simple DNS seeder in warnet

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#21]
Not sure if this makes sense, but something we should explore

**Comment by willcl-ark** [comment]
@pinheadmz can do this with `named` and a old-fashioned zone file if neeeded. We don't think it's really that important as loading a pre-defined topology is likely the more-common use-case.

**Comment by willcl-ark** [comment]
We had this but removed it.

Perhaps we will re-add later, but closing for now.
