### ISSUE TITLE
Add copy file command to warcli

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#210]
It would be useful to copy files from and to tanks.

I propose that we follow the pattern of `scp`, `docker cp` and `kubectl cp` by putting `tank:` in front of the path that for the tank.

Examples:

Copy from tank - `warcli cp 0000001:/etc/hosts /tmp`
Copt to tank - `warcli cp /tmp 0000001:/etc/hosts`

**Comment by willcl-ark** [comment]
I think we can close this now probably. We are loading config using `configMap`, and users can copy files with `kubectl cp <source> <destination> -n <namespace> <pod-name>:<path>`

**Comment by josibake** [comment]
+1, I don't know if I'd even want to expose this in warnet cli. For power users / development / niche use cases where copying is needed , kubectl cp works great.
