### ISSUE TITLE
Deploy warnet on other networks

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#22]
Signet, testnet. This is a way of just remote controlling and collecting logs for a group of nodes

**Comment by pinheadmz** [comment]
The `Warnet` class has property `self.bitcoin_network` with default "regtest" but we'll need to override (or replace) the line in templates/bitcoin.conf as well

**Comment by willcl-ark** [comment]
Is this actually something we ever want to implement? The _only_ use case I can see vs regtest is connecting it to public signet, which I don't think we should support?

CC @josibake @pinheadmz @m3dwards

**Comment by m3dwards** [comment]
While developing scaling ln I had a few conversations with groups such as lightning node implementations and wolf accelerator and also the people behind plebnet and zebedeenet and there were various use cases for spinning up a network that would be beneficial on more than just regtest.

Signet/testnet is useful for people wanting to run some nodes to test their applications against (such as node management tools) but also have them connect to a larger network.

Custom signets (plebnet and zebedeenet) are useful as an education and exploration tool. Something that we envisaged with scaling ln was to have it help facilitate collaboration between nodes. Such as an API that you could call to request a node open a channel with you or provide you with an invoice.

I don't know if Warnet wants to cover these use cases or stay more focussed. I think it would be nice to support.

**Comment by willcl-ark** [comment]
Perhaps the play here if we want it should be to switch warnet to signet, then we can afterwards add connecting to custom signets?

I have a feeling this might be more difficult than it sounds though, mainly because of the test framework changes needed...

**Comment by willcl-ark** [comment]
Implemented in #538
