### ISSUE TITLE
Set custom time in network

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#231]
I took a look at doing this, and it seems like [ntp](https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/) can be compiled with a simulator module, `ndptsim` if done manually, hooray! https://www.eecis.udel.edu/%7emills/ntp/html/ntpdsim.html

Unfortunately I was unable to get it to configure:

```fish
will@will-ubuntu in ~/Downloads/ntp-4.2.8p17
✗ ./configure --enable-simulator | rg error
checking whether strerror_r is declared... yes
checking whether strerror_r returns char *... yes
configure: error: could not locate pthread_detach()
```

I have pthread.h installed:

```fish
will@will-ubuntu in ~/Downloads/ntp-4.2.8p17 took 6s
₿ fd -uu pthread.h /usr/
/usr/include/boost/interprocess/sync/posix/pthread_helpers.hpp
/usr/include/boost/thread/pthread/pthread_helpers.hpp
/usr/include/pthread.h
/usr/share/python3-pycparser/fake_libc_include/pthread.h

will@will-ubuntu in ~/Downloads/ntp-4.2.8p17
₿ rg pthread_detach /usr/include/pthread.h
269:extern int pthread_detach (pthread_t __th) __THROW;
```

So, not entirely sure how to approach this direction further for now...

**Comment by mplsgrant** [comment]
@willcl-ark What if we ran an NTP server inside warnet, and then had all containers look to our NTP server to get their network time?

**Comment by willcl-ark** [comment]
Haha, I think @pinheadmz has mentioned this before...

Also, saw a timely tweet on this yesterday: https://x.com/Rob1Ham/status/1793363163166998656

**Comment by willcl-ark** [comment]
Closing as stale
