### ISSUE TITLE
Load and run scenarios at startup

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#25]
The user should be able to start the simulation with scenarios, such as the mining heartbeat and transaction activity generator

**Comment by pinheadmz** [comment]
something like `warnet --start=miner-std` ?

**Comment by josibake** [comment]
this could also be a UI, where you get a description of what the scenarios do and a way to pick the scenarios they want to run on the network.

A scenario is a set of commands to run on the network.

**Comment by josibake** [comment]
Closing for now, scenarios are launched via `warnet run` so its trivial for a user to write a bash script to `warnet deploy && warnet run <scenario>`
