### ISSUE TITLE
Create a `PyNode` agent

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#27]
Use pynode for more flexible control of a P2P node. This is useful for creating specific behaviors that might be difficult if using bitcoin core

**Comment by willcl-ark** [comment]
Perhaps this can be closed with the P2P_Connection node style?

**Comment by josibake** [comment]
Yeah, and I think the ultimate goal is to eventually generalise the commander so it can be used to inject any script the user wants to run. this would allow a clever user to create whatever they want for a lightweight "pynode".
