### ISSUE TITLE
Define better terms in the README

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#30]
So far, we are using the following terms:

* **Topology**: setting up a network and defining node connections (including not at all)
* **Personas**: a persona consists of everything you want to start a node with. This includes:
  * A wallet, preloaded with interesting UTXOs
  * A peers.dat file
  * A bitcoin.conf
  * .. basically a bitcoin datadir
  * We've also been calling these **Tanks**
* **Scenario**: a series of RPC calls / node interactions / topology mutations
  * scenarios can be running forever or a set duration
  * scenarios can involve one or more nodes, or the entire network

Should anything else that's helpful and document all of this in the readme

**Comment by pinheadmz** [comment]
• Tank: a dockerized bitcoind node 🔫

**Comment by josibake** [comment]
> • Tank: a dockerized bitcoind node 🔫

or lightning :eyes:

**Comment by josibake** [comment]
lets call personas profiles

**Comment by willcl-ark** [comment]
I think we can close this out now
