### ISSUE TITLE
Error on K8s shutdown

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#300]
See https://github.com/bitcoin-dev-project/warnet/actions/runs/8146627320/job/22265539387?pr=299#step:7:667 (also this doesn't fail test).

@m3dwards

**Comment by pinheadmz** [comment]
Fix for this might be in the connect edges branch

**Comment by pinheadmz** [comment]
https://github.com/bitcoin-dev-project/warnet/commit/d0af101f1417684a4fcf097ea0040fe18fded150



?

**Comment by willcl-ark** [comment]
Sweet, it very well might have been. I will watch out for it again...
