### ISSUE TITLE
Clean up and update docs for v1.0 release

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#308]

**Comment by Anyitechs** [comment]
Hi @pinheadmz, I will like to work on the documentation. Can you provide more details on the issue?

**Comment by pinheadmz** [comment]
Hi @Anyitechs thanks for tuning in! I think the most changes have been in kubernetes deployment. See `running.md` for the current docs which are out of date. The commands we use now are in the `/justfile` and can either be documented explicitly or we can recommend installing https://github.com/casey/just

Besides this, having someone just read through the docs and try to do everything they describe to make sure the commands still work would be a huge help.

**Comment by Anyitechs** [comment]
Thank you for the response @pinheadmz. I've cloned the repo and going through it at the moment. I'll send in a PR draft asap.

**Comment by Anyitechs** [comment]
Hi @pinheadmz, I opened a draft PR [here](https://github.com/bitcoin-dev-project/warnet/pull/342).

Let me know if there's anything I'm missing or needs to clean up.

**Comment by pinheadmz** [comment]
irelevant with new server model, all docs need refresh anyway
