### ISSUE TITLE
docs, docs, docs! 

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#31]
tons of examples. this tool is only useful if people can use it with minimal overhead, otherwise people will revert to doing their own setups.

**Comment by pinheadmz** [comment]
~README needs updated commands from https://github.com/bitcoin-dev-project/warnet/issues/37~

~also on macos requires https://github.com/chipmk/docker-mac-net-connect~

~and how to run a scenario!~

^^ done

**Comment by pinheadmz** [comment]
docs for prometheus / grafana needed now
