### ISSUE TITLE
catch fewer errors

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#317]
I think we need to be less afraid to raise exceptions. try/except blocks like the one below are counter productive. In [recent CI runs](https://github.com/bitcoin-dev-project/warnet/actions/runs/8397548114/job/23001021641?pr=315#step:7:724) for example, `wait_for_health()` fails, meaning `apply_network_conditions()` is just skipped, but the test continues to run along.

Somewhat related to https://github.com/bitcoin-dev-project/warnet/issues/198

https://github.com/bitcoin-dev-project/warnet/blob/44102004f9535bcc82a67b71de4138bfd826bb78/src/warnet/server.py#L472-L485

**Comment by matthew-chaincode** [comment]
Hi this is a test comment that is very spammy. I should be blocked and banned for 24 hours

**Comment by willcl-ark** [comment]
Fixed in /dev branch
