### ISSUE TITLE
Recent docker updates broke our healthcheck

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#318]
Recent docker updates have affected our CI because we install latest versions. By [pinning the previous verions of all the docker stuff](https://github.com/bitcoin-dev-project/warnet/pull/315/commits/71381dda8fc7f6660c9f08b26f000d68045f8394) I was able to at least get sucesful health checks in ci. This may be ok for now but we should figure out why the docker updates broke our healthchecks

[Old working versions](https://github.com/bitcoin-dev-project/warnet/actions/runs/8348374616/job/22850127237#step:3:116):
```

Get:1 https://download.docker.com/linux/ubuntu jammy/stable amd64 containerd.io amd64 1.6.28-2 [29.7 MB]
Get:2 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-buildx-plugin amd64 0.13.0-1~ubuntu.22.04~jammy [29.5 MB]
Get:3 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-ce-cli amd64 5:25.0.4-1~ubuntu.22.04~jammy [13.7 MB]
Get:4 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-ce amd64 5:25.0.4-1~ubuntu.22.04~jammy [24.3 MB]
Get:5 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-compose-plugin amd64 2.24.7-1~ubuntu.22.04~jammy [12.1 MB]
```

[New broken versions](https://github.com/bitcoin-dev-project/warnet/actions/runs/8397548114/job/23001021760#step:3:116):
```
Get:1 https://download.docker.com/linux/ubuntu jammy/stable amd64 containerd.io amd64 1.6.28-2 [29.7 MB]
Get:2 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-buildx-plugin amd64 0.13.1-1~ubuntu.22.04~jammy [29.5 MB]
Get:3 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-ce-cli amd64 5:26.0.0-1~ubuntu.22.04~jammy [13.8 MB]
Get:4 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-ce amd64 5:26.0.0-1~ubuntu.22.04~jammy [25.1 MB]
Get:5 https://download.docker.com/linux/ubuntu jammy/stable amd64 docker-compose-plugin amd64 2.25.0-1~ubuntu.22.04~jammy [12.1 MB]
```

**Comment by willcl-ark** [comment]
WTH docker!?

I will try and investigate why it's broken. Did it also break locally for you?

**Comment by pinheadmz** [comment]
Fine locally. I don't reinstall docker every time I run tests, like CI
