### ISSUE TITLE
make functions async, where it makes sense

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#34]
There is a lot of things we could do async , and some things we may need to do to get the scenarios correct

**Comment by willcl-ark** [comment]
We are effectively doing this by runinning some actions in threads: https://github.com/bitcoin-dev-project/warnet/blob/243f31229757047c50c4f8d64c311f02132b2a04/src/warnet/warnetd.py#L143-L156 and https://github.com/bitcoin-dev-project/warnet/blob/243f31229757047c50c4f8d64c311f02132b2a04/src/warnet/client.py#L72-L106

and some things using subprocess: https://github.com/bitcoin-dev-project/warnet/blob/243f31229757047c50c4f8d64c311f02132b2a04/src/warnet/warnetd.py#L233 and https://github.com/bitcoin-dev-project/warnet/blob/243f31229757047c50c4f8d64c311f02132b2a04/src/warnet/warnet.py#L101-L115

IMO async is not worth the complexity

**Comment by josibake** [comment]
closing this since most of the concerns seem to be addressed
