### ISSUE TITLE
Ruff CI does not appear to be checking PR branch

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#351]
ref: https://github.com/bitcoin-dev-project/warnet/pull/350#issuecomment-2077878932

**Comment by mplsgrant** [comment]
I wonder if we should separate out our CI in to a `pull_request_target` section and a `pull_request` section. I see that some of the workflow requires github secrets, and so I think that means it must use `pull_request_target`. The ruff workflow does not need secrets which means we can package it into an `on: pull_request` workflow and that would help us avoid this issue.

**Comment by willcl-ark** [comment]
I think this should be solved by the recent CI updates, closing for now...

(p.s, I do' kinda like the idea of having a seperate workflow just using `pull_request` for ruff, but I CBA personally to create the dependant workflows, so leaving for now. Would probably review such a PR though)
