### ISSUE TITLE
Ruff CI and external code

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-dev-project/warnet#357]
# Issue
The ruff CI check fails when I copy/paste the [replacement cycling functional test](https://github.com/ariard/bitcoin/blob/30f5d5b270e4ff195e8dcb9ef6b7ddcc5f6a1bf2/test/functional/mempool_replacement_cycling.py#L6) into our scenarios folder.

# Cause
Functional tests written by external authors do not necessarily conform to ruff's linting standards, and our CI won't pass unless ruff is happy.

# Possible solutions
1. Run ruff against other people's functional tests, altering their formatting to make ruff happy (current solution)
2. Add the `scenarios` folder to ruff's exception list
3. Create an `external` folder within scenarios to hold external scenarios, and add `external` to ruff's exception list

**Comment by josibake** [comment]
Id argue against 1 unless we are supplying an automatic formatter for people. Seems like it would just discourage people from writing scenarios and I don't see a lot of value anyways in ensuring scenarios are well formatted? 3 seems nice, or even just 2 for simplicity.

**Comment by mplsgrant** [comment]
I propose the simplicity option here: https://github.com/bitcoin-dev-project/warnet/pull/359

We currently have a single folder, and I figure keeping it simple for now will give us the opportunity to create more complex folder structures as specific needs arise.
