### ISSUE TITLE
something broke

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#37]
```
$ python connect_nodes.py
/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/matthewzipkin/Desktop/work/warnet/connect_nodes.py': 
[Errno 2] No such file or directory

```

**Comment by josibake** [comment]
Hm, looks like you don't have @willcl-ark 's new changes for installing via pip. What I'd recommend:

* Nuke your .venv file, if you have one with `rm -rf .venv`
* Nuke your docker containers (whichever command you've been using)
* pull main and run `pip install -e .` and then type `warnet`

**Comment by pinheadmz** [comment]
ok works thanks
