### ISSUE TITLE
build-test fails arbitrarily 

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-dev-project/warnet#374]
# Issue
build-test fails here...

 https://github.com/bitcoin-dev-project/warnet/actions/runs/9306448844/job/25616111319#step:4:2456

But, it passes on re-run...

https://github.com/bitcoin-dev-project/warnet/actions/runs/9306448844/job/25617440477#step:4:3647 

# Possible causes 
Appears to be some kind of issue on  the 'remote provider' end:

````
build-test
Received request to deprovision: The request was cancelled by the remote provider.

````

_Originally posted by @mplsgrant in https://github.com/bitcoin-dev-project/warnet/issues/369#issuecomment-2140381012_

**Comment by willcl-ark** [comment]
This is a GitHub Actions issue, been going on for 2 days now. Going to close here :)

**Comment by willcl-ark** [comment]
See e.g. https://github.com/actions/runner-images/issues/9848#issuecomment-2137525256
