### ISSUE TITLE
Add some `warcli attack` methods

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#378]
could e.g.

- send an `addr` message with junk addrs
- send an `addr` message with eclipse addrs
- ?

**Comment by matthew-chaincode** [comment]
hi this is another spammy comment, i should be blocked and banned

**Comment by josibake** [comment]
Concept NACK-ish on this. Ideally, a scenario file deployed by a commander can do _anything_ , so we don't need to overload the CLI for this. Attack commands in the CLI is also pretty specific to a war games scenario, and perhaps not generally useful in warnet.

Longterm, I'd prefer the CLI be generally useful for all warnet users and everything else be modelled through scenario scripts.
