### ISSUE TITLE
warcli scenarios stop: add `--all` flag

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#403]
because you might have a bunch running and who can be bothered to copy/paste all those little PID numbers

**Comment by pinheadmz** [comment]
also, now that we have names for running scenarios, maybe we can stop them by name as well. I think we might not even need to enforce name-uniqueness like `warcli stop tx_flood` would stop ALL tx_flood scenarios that are running, even multiple in parallel

**Comment by josibake** [comment]
Scenarios now run as pods, and the warnet command has been changed to `warnet run <scenario file>` and `warnet stop <scenario file>` or `warnet stop` which brings up a selector and allows you to choose `all` as a menu option, closing this as resolved.
