### ISSUE TITLE
Service refactoring

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#411]
See: [WarnetServices.pdf](https://github.com/user-attachments/files/16264976/WarnetServices.pdf)

Services should be split into core and none core.

Core Services:

- Logging
- Metrics
- Grafana
- Dashboards
- Lightning
- Bitcoin

None Core Services:

- SimLN
- Circuit Breaker

Services should be a python file and can be invoked from the cli. Similar to scenarios.

**Comment by willcl-ark** [comment]
Concept ACK

**Comment by m3dwards** [comment]
Doesn't apply to new architecture
