### ISSUE TITLE
Warcli Init command

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#412]
Add a command to warcli that will initialise a directory with example files for running a warnet simulation.

This will enable people to run warnet by just installing (or running) the warnet cli without having to clone the warnet repository.

Envisioned directory structure:

![Screenshot 2024-07-17 at 13 03 36](https://github.com/user-attachments/assets/b6ae58db-b6fa-4fd3-a4a8-30c6666b1ae0)

**Comment by willcl-ark** [comment]
I _think_ #377 may handle this?

```bash
pip install warnet
warcli setup
warcli cluster start
warcli network start
```

**Comment by josibake** [comment]
We have the Quickstart menu and also `warnet init`/`warnet create` commands. Could potentially drop one of those commands/ rename ? Leaving this open for now, as our current CLI commands are perhaps not sufficient, and adding the Tabconf milestone. @m3dwards can you take a look at the current CLI options and update this issue with what you think is missing or suggestions for improving?

**Comment by m3dwards** [comment]
What we have now is quite close to this vision. 

Perhaps just add a network create command to create a new network.

**Comment by josibake** [comment]
We have `warnet deploy ./path/to/network/dir` and each new project includes the example 6_node_network. Are you envisioning something different here? 

I am trying to keep it so are `deploy/run` commands _always_ take a path to a local file and do not rely on any defaults hidden in warnet, but happy to revisit that if you have a different use case in mind.

**Comment by m3dwards** [comment]
I think we are on the same page and have realised the vision. Closing.
