### ISSUE TITLE
quick_start.sh issues with MacOS

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#417]
1. The script assumes user has minkube installed when docker desktop will suffice (unrelated, minikube v1.22 and v1.23 both fail on macos for different reasons, and I had to install a [patch](https://github.com/kubernetes/minikube/issues/19173#issuecomment-2209193041) just to get it working.)
2. Current user in docker group: not needed for macOS or the command just fails anyway
3. Berkeley Packet Filters: I dunno what this is! But by bypassing the check in quick_start I was able to start...

**Comment by mplsgrant** [comment]
1. We could check for minikube, then if that fails, check for docker desktop
2. Docker group - Which conditions do we need the user in the docker group? 
* Linux Rootless - not needed (I think)
* Mac OS - not needed
* Linux standard - needed 
4. Berkeley Packet Filters - I want to incorporate trace points, but I am using zmq for the moment: https://github.com/bitcoin/bitcoin/blob/master/doc/tracing.md

**Comment by willcl-ark** [comment]
Removed these three things for now in https://github.com/bitcoin-dev-project/warnet/commit/61255717ac2966448843ad4b5bffcc9989de4b5c
