### ISSUE TITLE
Turn off auto-restart 

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-dev-project/warnet#438]
During a battle on warnet, we want the nodes that go down to stay down. 

How do we turn off auto-restart for those nodes?

Or, do we monitor "uptime" in grafana and look for drop-to-0?

**Comment by adamjonas** [comment]
Assuming this can be added as an option, yes?

**Comment by pinheadmz** [comment]
We can add a per-tank flag set in the graph file
