### ISSUE TITLE
explore using "shadow" as a simulation backend for warnet

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#45]
shadow-bitcoin-plugin is a project for doing large scale bitcoin simulations. the repo is unmaintained , but might be worth seeing if we can hook it up as a backend as a feature.

https://github.com/shadow/shadow-plugin-bitcoin
https://shadow.github.io/

### why

the tool already does *a lot* of what we want, like simulating latency, node sizes, network jitter, etc. it allows you to define the a network using networkx (graphml) and has an emphasis on determinism and reproducibility. because of how we've modularized warnet, should be fairly simple to offer this as a backend to the user.

### why not just use this instead of docker?

shadow seems to solve one use case: large scale simulations. what it doesn't provide (or its unclear how) is a way to run a long-running setup that the user can interact with. it also doesn't seem easy to hook up live monitoring tools and dashboards. sure, we _could_, but sticking with docker allows us to use off the shelf stuff like prom/grafana, and seems a better fit for the "lets run stuff for a long time".

**Comment by willcl-ark** [comment]
I don't think switching to shadow is on the roadmap currently
