### ISSUE TITLE
better configuration management

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#458]
today, any change I make requires re-building the rpc server image, pushing or loading it into a cluster, etc. if we move more of the configuration out of the rpc server and make it more the responsibility of the CLI , we could change config options without needing to redeploy the RPC server.

A few examples:

- tank resources, cpu and memory
- registry to pull from (e.g., bitcoindevproject)

**Comment by mplsgrant** [comment]
Another config item:

* set minikube vs docker-desktop

Possible rules for the config:
1. Any item set in the config file cannot be changed.
2. Any item not sent in the config file maybe set later, but once set, it cannot be changed.

**Comment by mplsgrant** [comment]
I think YAML solves this. Also, prompting the user for minikube vs docker-desktop in quickstart.
