### ISSUE TITLE
warcli start

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-dev-project/warnet#462]
- [ ] Create `warcli start` functionality
- [ ] Add install logging (the helm commands) to warcli start
- [ ] Run setup-minikube if needed
- [ ] Run `warcli deploy`
- [ ] Prompt the user to `warcli network start`

**Comment by josibake** [comment]
This is solved with the Quickstart menu, correct? Closing for now, if there is anything here not covered by Quickstart can you open it as its own issue?
