### ISSUE TITLE
Intermittent failure in test_logging.py

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#489]
see e.g. https://github.com/bitcoin-dev-project/warnet/actions/runs/10538628018/job/29201332463#step:7:182

**Comment by willcl-ark** [comment]
https://github.com/bitcoin-dev-project/warnet/actions/runs/10547706361/job/29220719560#step:7:1

**Comment by pinheadmz** [comment]
~Doesn't look like the connect logging script even executed before that check.~

nm it is running. Maybe we need to add a wait for 200 in there

**Comment by willcl-ark** [comment]
I think this will be fixed by #490 (and the direct-to-master push https://github.com/bitcoin-dev-project/warnet/commit/b3f7eeb75c64e77e22dba4c228143d4f75ef91c8 )
