### ISSUE TITLE
Refactor historic CVE images

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#508]
Lots of duplication in the current historic CVE images, would be nice to refactor this a bit into a common base image, where version specific changes are then applied as much smaller images, e.g.,

```
FROM warnet-base-image

# specific fixes with comments
```

Additionally, it would be nice to document the specific changes for each image. This is with the idea we may need to rebuild/edit these images at some point in the future, so just some good housekeeping to ensure maintainability.

Lower priority for now.

**Comment by willcl-ark** [comment]
> This is with the idea we may need to rebuild/edit these images at some point in the future, so just some good housekeeping to ensure maintainability

The images can be re-built now or any time in the future as they are currently in #498 (simly `docker build ...`), but I will happily review a PR refactoring commonality out of them if you see value in that.

**Comment by willcl-ark** [comment]
closed by #539
