### ISSUE TITLE
Clean up dead code

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#510]
Made lots of changes in Italy re: moving stuff around, renaming files, etc. Now there is some dead code, specifically:

* scenerios.py
* network.py
* namespaces.py

and some new files:

* control.py
* deploy.py

A lot of this was me moving stuff around, so I'll take a stab at cleaning up and trying to keep the code DRY

**Comment by willcl-ark** [comment]
@josibake Can this be closed out now since #521

**Comment by josibake** [comment]
would like to see #528 merged before closing this
