### ISSUE TITLE
pass through scenario file help options

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#512]
If I run `warnet run ./scenarios/mining_std.py` , it's difficult to know what options are available for the python test. We could do something like `warnet run ./scenarios/mining_std.py --help`, which would then show the arguments for that script, but this somewhat assumes all of the scripts have some sort of help option with them, which definitely won't be the case once we enable running _anything_ via `warnet run <path to executable>`.

Perhaps simpler would be let the user determine the arguments for the script without needing to go through warnet, something like `./scenarios/mining_std.py --help`. This doesn't work today because the scripts aren't executable but we can change that so that when the directory is created for the user all of the default scenarios are created as executable.

Another issue with this approach is the bitcoin python test framework class spits out a bunch of irrelevant options, e.g.:

<img width="735" alt="image" src="https://github.com/user-attachments/assets/313cd68a-8da4-43d7-aeed-249406d0142c">

So at a minimum id propose we:

- modify the WarnetTestFramework / commander code to not show help options from the bitcoin test framework
- make it so all scripts in scenarios/ are executable by default

Curious to hear other suggestions before jumping in with a PR for this?

**Comment by willcl-ark** [comment]
I actually did this in Italy but can't find the branch, sorry. My approach was to use a second `ArgParse` instance, to return only help options from the current file, and not sub-classed help options.

> make it so all scripts in scenarios/ are executable by default

Did this in https://github.com/bitcoin-dev-project/warnet/pull/506 already

IMO think it's very reasonable to expect users to know how to run their executables.

**Comment by josibake** [comment]
> I actually did this in Italy but can't find the branch, sorry. My approach was to use a second ArgParse instance, to return only help options from the current file, and not sub-classed help options.

Nice, if you have it, I think that's exactly what I'm looking for. And agree, if the user is writing their own program it's their responsibility to document it.

This makes it so warnet run <file> just runs the file, which is nice.

**Comment by willcl-ark** [comment]
Opened in #522
