### ISSUE TITLE
Error creating project: [Errno 30] Read-only file system: '/Us'

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#514]
Just following instructions! @josibake 

Probably fixed by #500 

```
Do you want to create a new project? [Y/n]: 

Enter the project directory path [/Users/matthewzipkin/Desktop/work/warnet]: /Users/matthewzipkin/Desktop/qtwntest2

Do you want to create a custom network? [Y/n]: 

Enter the network name: ugh

How many nodes would you like? [15]: 2

How many connections would you like each node to have? [8]: 1

Which version would you like nodes to be by default? (27.0, 26.0, 25.1, 24.2, 23.2, 22.2) [27.0]: 27.0

Creating project structure...
Error creating project: [Errno 30] Read-only file system: '/Us'
An error occurred while running the quick start script:

[Errno 30] Read-only file system: '/Us'


Please report this to https://github.com/bitcoin-dev-project/warnet/issues
```

**Comment by willcl-ark** [comment]
What type of filesystem is this? It works just fine for me.

I don't think we can particularly control whether the user has some weird read-only filesystem (or at least, it's not productive for us to handle all such edge cases)

![image](https://github.com/user-attachments/assets/3105e4ef-6dc1-441c-b102-b944acbfd94f)

**Comment by pinheadmz** [comment]
it's macOS, is it possible there is a string slicing issue happening? `/Us` is the first three characters of the path I tried to use

**Comment by willcl-ark** [comment]
Does this still happen after #500 @pinheadmz ?
