### ISSUE TITLE
"network connected" is gone

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#515]
solution: incorporate into `warnet status` and also add a machine-readable `--json` flag

**Comment by josibake** [comment]
We still have a `_connected` function that is no longer exposed in the CLI, should be easy to add it to the `warnet status` page. For the machine-readable `--json` flag, is this for running tests in CI, i.e., wait to run a test until the network is connected?

**Comment by pinheadmz** [comment]
Actually the json maybe isn't necessary. I forgot the tests actually import the _connected() function and run that directly. So even though the cli command is missing the tests have continued using it that way.

**Comment by josibake** [comment]
Great! If you still feel it's needed for the cli user, we can easily add it to the status page.
