### ISSUE TITLE
CI image pipeline improvements

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#520]
We should build images in CI and use those directly. Ideally, once a PR gets merged to main, it should also build and push images to dockerhup (post-merge action?).

I'm sure this is a well established patterns in other projects, so likely something we can pull from other places. The goal here is to minimise differences between what we are testing vs what's in our public docker hub and get our PR / review / merge process to not involve manual steps, like changing image names from dev -> latest before merging.

Adding as a backlog, not high priority.

**Comment by willcl-ark** [comment]
Which images are you talking about here specifically? This would be:

- easy for commander
- absolute PITA for 6 cross-platform bitcoin core images

**Comment by josibake** [comment]
per https://github.com/bitcoin-dev-project/warnet/pull/506#discussion_r1742455141 , this is referring to the commander image. perhaps we start there and then look at the bitcoin core images separately ?

**Comment by willcl-ark** [comment]
Sure, we did this before for the RPC image and I could easily port it over for the Commander

**Comment by willcl-ark** [comment]
Done in #523
