### ISSUE TITLE
install/connect logging should be warnet CLI commands

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#526]
Because our new model is: 

`pip install warnet`
`cd some directory`
`warnet create ...`
and so forth.

So the user shouldn't need to know where on their computer the `install_logging.sh` script is

**Comment by josibake** [comment]
Agree, and ideally they aren't even their own cli commands, but its an option set in a config file (e.g., the network.yaml) or something implicit like if you specifying logging on at least one node, then it auto installs logging.

**Comment by pinheadmz** [comment]
port forwarding too though! which is tricky because its a blocking process and ive found that port 3000 for grafana will occasionally drop out and either come back on its own or need to be reset

**Comment by josibake** [comment]
> port forwarding too though!

paging @m3dwards , I think its time to kill port-forwarding with fire 😬 probably not essential for Tabconf, but I do think if we got some basic ingress/egress working at least for the dashboards, it would make the logging stuff _much_ simpler from the user perspective (and ours).

**Comment by m3dwards** [comment]
Might be worth a discussion on pros / cons on ingress.

Downsides that come to mind is it's another small step to enable on minikube (just works on docker desktop) and that on cloud you get billed for public IP addresses and load balancers.

Benefit of ingress is it allows anyone to connect to the same service which is nice and might be a bit more reliable than port-forwarding.

**Comment by josibake** [comment]
started a discussion here re: port-forwarding vs ingress: https://github.com/bitcoin-dev-project/warnet/discussions/529
