### ISSUE TITLE
"warnet down" takes a long time for large network

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#527]
I think its because we are "helm uninstall"-ing one tank at a time in a loop. I know it won't work with "default" namespace but for sure, `namespace delete` worked a LOT faster

**Comment by willcl-ark** [comment]
Is it not fork-observer❓

**Comment by josibake** [comment]
Might be possible to tune our helm commands a bit, but also doing a namespace delete should work. One thing to keep in mind: if we deploy stuff with helm and then delete it with something else, we might leave helm in a confused / borked state.

**Comment by pinheadmz** [comment]
we learned in italy that we cant delete the `default` namespace

**Comment by willcl-ark** [comment]
Helm has state? 

I thought it was a yaml masher only?

**Comment by willcl-ark** [comment]
I think I have something for this, inadvertently discovered when trying to teardown my Caddy deployment...

**Comment by josibake** [comment]
It would be great to speed up `warnet down` but I don't think this is a priority before Tabconf, unless we are talking about wait times that make development and testing unbearable.

I'd also suggest we investigate tuning helm first before going straight to managing the teardown ourselves in python.

**Comment by willcl-ark** [comment]
https://github.com/BarelElbaz/helm-delete-all

If we really want this to be faster, this plugin may be a solution

**Comment by pinheadmz** [comment]
closed by #550
