### ISSUE TITLE
Rebuild old CVE images with support for signet

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#532]
Per #503 , signet was introduced in 0.21.0 which means we can't use the signet approach for old CVE images. I took a look at the PR for signet and it seems relatively straightforward to back port. Going to take a stab at back porting images, starting with the oldest one first. Depending on how hard this is, I'll either:

- give up
- have all of the images back ported by Thursday of next week

This unblocks being able to use a signet miner to restrict other players from mining in a multi-player setting.

## Images to backport

- [x] 0.16.1
- [x] 0.17
- [x] 0.19.2
- [x] 0.20

**Comment by josibake** [comment]
Images all built, working on refactoring the CVE script a bit and then will open a PR

**Comment by pinheadmz** [comment]
Once your images are all done, they can be tested by adding them to the signet test in #538
