### ISSUE TITLE
bitcoin.conf ain't quite right...

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#54]
For starters, we are using the same conf file in each tank:

https://github.com/bitcoin-dev-project/warnet/blob/030b3b128a43323307c0f8fde39df48c46824ffc/src/warnet/docker_compose.py#L129-L130

When I tried to fix this myself it kinda worked but `regtest=1` was missing from all the configure files and everything tried to sync main!

**Comment by willcl-ark** [comment]
So this fixes it, but its a bit hacky, as it doesn't use the proper `id` property from the graph, only the iterator...

```diff
diff --git a/src/warnet/docker_compose.py b/src/warnet/docker_compose.py
index 93cb424..424c533 100644
--- a/src/warnet/docker_compose.py
+++ b/src/warnet/docker_compose.py
@@ -126,8 +126,7 @@ def generate_docker_compose(graph_file: str):
 
     for i, node in enumerate(nodes):
         version = node["version"]
-        conf_file = node.get("conf", "bitcoin.conf")
-        conf_file_path = f"./config/{conf_file}"
+        conf_file_path = f"./config/bitcoin.conf.{i}"
 
         # Check if the configuration file exists
         if not os.path.isfile(conf_file_path):
```
