### ISSUE TITLE
self.nodes[] in scenarios should accept node names

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#549]
So it will match the graph specified in network.yaml

We may be able to preserve backwards compatibility by making self.nodes a dict and indexing nodes by *both* their index number and their name?

**Comment by josibake** [comment]
+1, I found it pretty confusing to be specifying tank names in the config/logs/bitcoin rpc commands, but then needing to switch to index when using scenarios and tests.

could backwards compatible, but I generally prefer having one way to do things.
