### ISSUE TITLE
Add (and remove) single nodes

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#57]

**Comment by josibake** [comment]
Could do this in a very simple way by appending to docker-compose, but I don't think we need this by Thursday

**Comment by pinheadmz** [comment]
I think this is about adding new nodes after a network is already running. So docker compose might be too late.

**Comment by willcl-ark** [comment]
Going to close this for now as stale.

If it comes up again, we can open a new issue or PR

**Comment by josibake** [comment]
This also _mostly_ works already: I've done it by just running helm commands to deploy the bitcoincore chart into the same namespaces as a currently running network. If this does end up being a use case, we could just add a doc or a wrapper command around helm for one off deployments.
