### ISSUE TITLE
Add ingress

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#587]
This will be useful for dashboard/service access, which currently uses a port from localhost:2019 into the caddy pod.

Linked to #531 and #208

**Comment by josibake** [comment]
another thing we wouldn't have to worry about if we added ingress and stopped using port forwarding: #586

**Comment by m3dwards** [comment]
Completed it mate.

![](https://c.tenor.com/fj32-lmyDrYAAAAC/tenor.gif)
