### ISSUE TITLE
How do we feel about type annotation

### ISSUE THREAD

**Issue by rustaceanrob** [bitcoin-dev-project/warnet#593]
In working with the `test_framework` on Tuesday I noticed I was following function signatures to try to find which types were used as arguments. Perhaps that is an LSP issue on my end, but I think adding type annotations to function signatures makes the code more legible. If maintainers agree I will work on adding type annotations to `test_framework`

**Comment by pinheadmz** [comment]
`test_framework` is copied directly from Bitcoin Core so if we do make any changes to it, we'll have a maintenance burden if we want keep it up to date.

**Comment by rustaceanrob** [comment]
I may suggest the same in an issue there but I will close this, thanks
