### ISSUE TITLE
Create a mining scenario(s)

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#6]
This is a basic scenario for generating activity. It should have a node(s) that mine blocks in a way that stimulates maininet (once every 10 mins on avg). Optionally, this scenario could allow the user to specify certain parameters such as the avg time between blocks, etc, but it might be better to just make these as separate scenarios.

**Comment by pinheadmz** [comment]
closed by https://github.com/bitcoin-dev-project/warnet/pull/40
