### ISSUE TITLE
Adding lightning specific attributes to the XML file

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#61]
We need:

* lighting implementation type (this is to get the right docker image)
* version/commit hash (lets just stick with versions for now)
* lightning node alias (container name?)

**Comment by carlaKC** [comment]
All of this is going to go directly into the warnet graphml file:
* Add tag to `node` in graphml that indicates that it's a lightning node
* This tag can have attributes that are unique to the lightning node (as we do for bitcoin).

**Comment by willcl-ark** [comment]
We can add this stuff easily now and have a [`schema`](https://github.com/bitcoin-dev-project/warnet/blob/main/src/schema/node_schema.json) file to cross-check against, so I think we can close this out now?

As we need more ln-node properties we can add to the graph and schema.

**Comment by pinheadmz** [comment]
Dont close, ill implement it evetually. I think we need this for MIT

**Comment by pinheadmz** [comment]
oh whoops sorry wrong issue thought this was #227
