### ISSUE TITLE
default config file for each lightning impl

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#63]
similar to bitcoind we need a config file per each lightning node. we also need to update our bitcoin.conf to enable zmq

**Comment by carlaKC** [comment]
Probably not going to get to this as soon as I would have liked, dropping this in here so that it's available in the meantime. 

Updates for `bitcoin.conf`: 
```
# lightning!
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
```

LND:
```
# [bitcoind]
active=1
regtest=1
node=bitcoind
rpcuser=btc
rpcpass=passwd

# misc
norest=1
debuglevel=debug
accept-keysend=1
```

Values that we'll need to fill in when we generate the config:
```
zmqpubrawblock=tcp://(BITCOIN_CONTAINER):28332
zmqpubrawtx=tcp://(BITCOIN_CONTAINER):28333
externalip=(LIGHTNING_CONTAINER)

# [bitcoin]
rpchost=(BITCOIN_CONTAINER)
```
