### ISSUE TITLE
Create transaction activity scenario

### ISSUE THREAD

**Issue by josibake** [bitcoin-dev-project/warnet#7]
Scenario for making sure there is regular transaction activity on the network. Can serve as a base scenario for extending to more complex transaction activity

**Comment by pinheadmz** [comment]
Is this closed by `tx_flood` for MVP at least? more complexities and more scenarios can always be TODO'ed

**Comment by josibake** [comment]
tx_flood is pretty close , but what I _actually_ had in mind was more of a "heartbeat": a while true run that has random nodes sending txs and random nodes mining blocks every X-ish mins. This is so we have a heartbeat for the warnet while ln-sim is running their payment activities.

Is this something you could do by Friday? I'll assign to you for now but if you dont have bandwidth, lemme know and ill pick it up!

**Comment by josibake** [comment]
@pinheadmz do you want to take this for the thursday milestone? I can take it if not
