### ISSUE TITLE
get p2p messages from non-tank peers (e.g. onion addrs)

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/warnet#78]
the `warnet messages` function accepts two tank integers to get p2p messages, but those are collected by ipv4 address. If tanks connect over Tor, the messages are not stored by IP but by onion address. We can still get the files and parse the messages but right now the cli is only equiped to fetch by ipv4

**Comment by willcl-ark** [comment]
We could potentially close this while we are still temporarily Tor-free? 😢

**Comment by pinheadmz** [comment]
yeah
