### ISSUE TITLE
spin-up a fork-observer instance in the warnet docker-compose

### ISSUE THREAD

**Issue by 0xB10C** [bitcoin-dev-project/warnet#79]
The [fork-observer](https://github.com/0xb10c/fork-observer) tool visualizes the header tree of multiple nodes and which header/blocks nodes consider to be active/stale. This allows tracking forks and reorgs. For warnet, it could also highlight _stuck_  nodes. A live version of fork-observer is available on https://fork.observer.

![image](https://github.com/bitcoin-dev-project/warnet/assets/19157360/a97b170f-3eee-4fc2-be60-cb9a3685d93b)

While the tool is still  work-in-progress, I think it makes sense to have the option to spin up an instance along side the Bitcoin nodes and the grafana dashboard. The the configuration file for fork-observer can be generated from the XML file with the node information.

**Comment by 0xB10C** [comment]
As a first step, it might make sense to add a fork-observer CI job that builds a docker-image and pushes it to some registry.

**Comment by willcl-ark** [comment]
> As a first step, it might make sense to add a fork-observer CI job that builds a docker-image and pushes it to some registry.

Taking a go at that here: https://github.com/willcl-ark/fork-observer/actions/runs/6024172731/job/16342330596

**Comment by 0xB10C** [comment]
Some progress in https://github.com/bitcoin-dev-project/warnet/pull/87
