### ISSUE TITLE
Don't mount files from /tmp/ directories

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#86]
Currently we mount volumes (files) that are created and live in /tmp/ which are obviously ephemeral and could be erased at any time, don't do this:

https://github.com/bitcoin-dev-project/warnet/blob/9888538716f262b1441fb0751a83dfe380f67846/src/warnet/warnet.py#L119-L128

(I am in the process of adding a second like this, fork-observer)

**Comment by pinheadmz** [comment]
oh dang I thought we were copying files into the containers

**Comment by willcl-ark** [comment]
`volumes` is a mount. Also I think a config dir makes more sense anyhow, then we can use `docker-compose down` to stop (proper way?), and also give people easy access to their docker-compose.yaml, bitcoin core config files etc
